stages:
  - release

publish-binaries:
  stage: release
  image: ubuntu:22.04
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  before_script:
    - apt-get update && apt-get install -y curl jq unzip file
  script:
    - ./update.sh
    - ./publish.sh
